### Menu Configuration #####################
#
# Define the major menu sections and subsections in this file.
# Define where each page exists in a menu in each page's frontmatter.
# Define the order of each menu section in the `config/_default/params.toml` file with the `menuOrder` paramater
#
# See our documentation for more information about defining menus.
# https://docs.chef.io/style/front_matter/
#
# See Hugo's documentation about menus.
# https://gohugo.io/content-management/menus/
#
############################################


####
## Main Menu ##
####

[[main]]
title = "chef.io"
identifier = "chef"
url = "https://www.chef.io/"
weight = 10

[[main]]
title = "Blog"
identifier = "blog"
url = "https://www.chef.io/blog"
weight = 30

[[main]]
title = "Community"
identifier = "community"
url = "https://community.chef.io/"
weight = 40

[[main]]
title = "Training"
identifier = "training"
url = "https://www.chef.io/training"
weight = 50

[[main]]
title = "Downloads"
identifier = "downloads"
url = "https://www.chef.io/downloads"
weight = 60

####
## End Main Menu ##
####

####
## Resource pack menus
####

# [[alicloud]]
# title = "Alibaba Cloud"
# identifier = "inspec/resources/alicloud"

[[aws]]
title = "AWS"
identifier = "inspec/resources/aws"

[[azure]]
title = "Azure"
identifier = "inspec/resources/azure"

[[docker]]
title = "Docker"
identifier = "inspec/resources/docker"

[[elasticsearch]]
title = "Elasticsearch"
identifier = "inspec/resources/elasticsearch"

[[gcp]]
title = "GCP"
identifier = "inspec/resources/gcp"

[[habitat]]
title = "Habitat"
identifier = "inspec/resources/habitat"

[[k8s]]
title = "Kubernetes"
identifier = "inspec/resources/k8s"

[[mongodb]]
title = "MongoDB"
identifier = "inspec/resources/mongodb"

[[podman]]
title = "Podman"
identifier = "inspec/resources/podman"

[[rabbitmq]]
title = "RabbitMQ"
identifier = "inspec/resources/rabbitmq"
