### Menu Configuration #####################
#
# Define the major menu sections and subsections in this file.
# Define where each page exists in a menu in each page's frontmatter.
# Define the order of each menu section in the `config/_default/params.toml` file with the `menuOrder` paramater
#
# See our documentation for more information about defining menus.
# https://docs.chef.io/style/front_matter/
#
# See Hugo's documentation about menus.
# https://gohugo.io/content-management/menus/
#
############################################


####
## Main Menu ##
####

[[main]]
title = "chef.io"
identifier = "chef"
url = "https://www.chef.io/"
weight = 10

[[main]]
title = "Blog"
identifier = "blog"
url = "https://www.chef.io/blog"
weight = 30

[[main]]
title = "Community"
identifier = "community"
url = "https://community.chef.io/"
weight = 40

[[main]]
title = "Training"
identifier = "training"
url = "https://www.chef.io/training"
weight = 50

[[main]]
title = "Downloads"
identifier = "downloads"
url = "https://www.chef.io/downloads"
weight = 60

####
## End Main Menu ##
####

[[install]]
title = "Install"
identifier = "install"

[[profiles]]
title = "Profiles"
identifier = "profiles"

[[configure]]
title = "Configure"
identifier = "configure"

[[chef_tools]]
title = "Chef tools"
identifier = "chef_tools"

[[related]]
title = "Related projects"
identifier = "related"

[[reference]]
title = "Reference"
identifier = "reference"

[[resources]]
title = "Resources"
identifier = "resources"

    [[resources]]
    title = "Resource packs"
    identifier = "resources/packs"
    parent = "resources"
    weight = 20

    [[resources]]
    title = "Core resources"
    identifier = "resources/core"
    parent = "resources"
    weight = 30

    [[resources]]
    title = "Custom resources"
    identifier = "resources/custom"
    parent = "resources"
    url = "/profiles/custom_resources/"
    weight = 40