#######
## Site-level parameters
#######

#######
# menuOrder = The order of the menus are included in the left nav menu.
#             Menus are defined in the /config/_default/menu.toml file
#######

menuOrder = []

#######
# robots = The default robots config applied to each page in the robots meta tag.
#          See http://www.robotstxt.org/meta.html
#######

robots = ''

#######
# breadcrumbs = Whether breadcrumbs are enabled.
#               This must be set in the page frontmatter, too. See the content/_index.md file.
#               See https://gohugo.io/content-management/sections/#ancestors-and-descendants
#
# breadcrumb_base = adds additional links to the beginning of the breadcrumbs list. For example, to docs.chef.io.
#                   This accepts an array of tables. https://toml.io/en/v1.0.0#array-of-tables
#######

breadcrumbs = true

[[breadcrumb_base]]
breadcrumb = "Documentation"
url = "https://docs.chef.io"

#######
#
# Settings for the link and image render hooks.
#
# See:
# - https://www.veriphor.com/articles/link-and-image-render-hooks/
# - https://gohugo.io/render-hooks/links/
# - https://gohugo.io/render-hooks/images/
#
# render_hooks.link.errorLevel
#       ignore (default), warning, or error (fails the build)
#
# render_hooks.link.highlightBroken
#        true or false (default). Adds `broken` class to link in development env
#
# render_hooks.image.errorLevel
#        ignore (default), warning, or error (fails the build)
#
#######

[render_hooks.link]
errorLevel = 'warning'
highlightBroken = true

[render_hooks.image]
errorLevel = 'warning'
