#######
## Site-level parameters
#######

#######
# menuOrder = The order of the menus are included in the left nav menu.
#             Menus are defined in the /config/_default/menu.toml file
#######

menuOrder = ["about", "install", "configure", "profiles", "shell", "troubleshooting", "chef_tools", "related", "resources", "reference", "release_notes"]

#######
# robots = The default robots config applied to each page in the robots meta tag.
#          See http://www.robotstxt.org/meta.html
#######

robots = ''

#######
# breadcrumbs = Whether breadcrumbs are enabled.
#               This must be set in the page frontmatter, too. See the content/_index.md file.
#               See https://gohugo.io/content-management/sections/#ancestors-and-descendants
#
# breadcrumb_base = adds additional links to the beginning of the breadcrumbs list. For example, to docs.chef.io.
#                   This accepts an array of tables. https://toml.io/en/v1.0.0#array-of-tables
#######

breadcrumbs = true

[[breadcrumb_base]]
breadcrumb = "Documentation"
url = "https://docs.chef.io"

#######
#
# Settings for the link and image render hooks.
#
# See:
# - https://www.veriphor.com/articles/link-and-image-render-hooks/
# - https://gohugo.io/render-hooks/links/
# - https://gohugo.io/render-hooks/images/
#
# render_hooks.link.errorLevel
#       ignore (default), warning, or error (fails the build)
#
# render_hooks.link.highlightBroken
#        true or false (default). Adds `broken` class to link in development env
#
# render_hooks.image.errorLevel
#        ignore (default), warning, or error (fails the build)
#
#######

[render_hooks.link]
errorLevel = 'warning'
highlightBroken = true

[render_hooks.image]
errorLevel = 'warning'

#######
#
# versions:
#     Version data used to link to other releases and populate page layouts with version information.
#
# versions.this_version:
#     Data for this documentation version.
#
# versions.this_version.swiftype_search_products:
#     A list of product search strings. This populates a Swiftype meta tag on each page with product data
#     used to facet search results in docs.chef.io/search.
#     This can be overridden in the page frontmatter using the same property.
#
# versions.this_version.release_date:
#     The release date of the first major.minor.patch release.
#     This data is used to generate the <lastmod> tag in the sitemap.xml file.
#     If blank, it uses each page's Git Lastmod date.
#     If release_date is set, it uses the more recent date from Lastmod or release_date.
#     Use the ISO-8601 format: YYYY-MM-DD
#
# versions.version_selector:
#     Data for generating the version selector menu allowing users to switch between different doc versions.
#
# versions.version_selector.enabled:
#     Whether the version selector is enabled. true or false. Default is false.
#
# versions.version_selector.this_version_text:
#     The text that appears in the version selector menu indicating the version they're currently viewing.
#
# versions.version_selector.versions:
#     A list of objects that create links to other doc versions.
#
# versions.version_selector.versions.[].link_text
#     The text in the link to another doc version.
#
# versions.version_selector.versions.[].base_url
#     The base URL link to another doc version.
#     The page path is appended to the base URL, giving a link to the same page in the other version.
#
#######

[versions.this_version]
swiftype_search_products = [ "inspec-6" ]
#release_date = ""

[versions.version_selector]
enabled = true
this_version_text = "Chef InSpec 6"

[[versions.version_selector.versions]]
link_text = "Chef InSpec v 2.0"
base_url = "https://docs.chef.io/inspec/2.0"

[[versions.version_selector.versions]]
link_text = "Chef InSpec v 1.6"
base_url = "https://docs.chef.io/inspec/1.6"